### ISSUE TITLE
TM_Lib_Internal:: bufferMsg without function

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#826]
Data flow ends in this operator.
Buffer has no information after send operator is completed.

kr
Bernd

**Comment by JakobGartner** [comment]
This has been fixed. Regression error when transitioning to new buffer version. ("write" flag that tells the buffer to release its contents was sent to true when the bus was busy)

**Comment by BerndHekele** [comment]
Fix does not work:
![image](https://cloud.githubusercontent.com/assets/3288918/10559525/bc9474b4-74f2-11e5-9e85-efb97c776872.png)

I cannot debug into the lib function because of builder problems (I race a new issue for this behaviour. We still have an loading error in the lib #823 . Can you please have a lookat all aspects of the problem?

kr
Bernd

**Comment by BerndHekele** [comment]
I made a smaller model. Here debugging is posible. The data flow in question looks like:
![image](https://cloud.githubusercontent.com/assets/3288918/10559971/bf8f5562-74fc-11e5-9c28-dd1a61d620a0.png)

**Comment by JakobGartner** [comment]
OK,
I found the problem and can fix it quickly. The problem is about initialisation of the buffer if it is empty in the first cycle and the bus is not busy.

**Comment by JakobGartner** [comment]
done

**Comment by BerndHekele** [comment]
Solved
