### ISSUE TITLE
Emergency brake by level chang 

### ISSUE THREAD

**Issue by Farhangi** [openETCS/modeling#874]
an emergency brake will be triggered after the level Change(Level_2 -> NTC). (@32001 m)
![capture](https://cloud.githubusercontent.com/assets/2284296/10795449/1bac8bee-7d9a-11e5-9ddd-38a08098107a.PNG)
@JakobGartner 
@T12z

**Comment by JakobGartner** [comment]
I am not sure if the EM locations are already correctly calculated

**Comment by jokaICS** [comment]
Is there really an emergency message (Msg 15/16) involved, or do we just overpass the EoA?

**Comment by JakobGartner** [comment]
I am trying to answer the same question right now—

when I see the data, the value 500000 for the EOA looks strange, as we don’t have such a value in our data, with exception of the constant that defines the NTC speed profile.

An here it might then just be a scaling error in my constant?

**Comment by JakobGartner** [comment]
The MRSP we used for NTC was too short, hence as soon as we switched into NTC Level, we stop…

Fixed…

**Comment by BaseliyosJacob** [comment]
Dear all,

we have here again a system switch between an ETCS Level 2 and NTC with a previoius MA for Level 2.

I see 3 riks from my point of view:

1) the MA is to short until the switch.
2) Is the MA EOA before or after the switch (transition balise) from Level 2 and NTC (@jakobGärtner)
can you check it on the track data?
3) there is an issue between the computation of the MA in the track Atlas, Speed Suprervision and Mode and Level Management.

**Comment by JakobGartner** [comment]
There was a simple error in the workaround for NTC, which lead to the allowed speed being 0 at this location.

**Comment by Farhangi** [comment]
The bag is not yet fixed(emergency brake will be triggered)

And the train still runs with maximum Speed 40 km / h.

**Comment by JakobGartner** [comment]
Ok I have re-pushed the constant for NTC. If it doesn't work now its something else

**Comment by T12z** [comment]
By the way,
there was a discussion, whether speed profiles need some kind of end-marker, e.g. 0, 635 km/h or whatever. From SDM's point of view, profiles are always open ended and are limited by the MA. So an end-marker does not add anything, but may break things.

**Comment by JakobGartner** [comment]
So, should I 

(a) leave the end- marker in
(b) replace it by 0 at the location of the EOA
(c) put the speed from the prior section
(d) do something else?

**Comment by T12z** [comment]
You can (a) leave things as they are
You shall not (b) (c) generate things. In fact, a "valid" MRSP with 0 km/h may actually cause undefined behaviour.

If DMI requires some sort of End-Marker -- as long as it is past the MA, SDM should not give a continental.

From specification the MRSP-Array should only contain existing profiles (start-location + speed limit). Each profile ends at the next start-location or with the MA. It is also totally fine to pass in known profiles beyond the MA.

**Comment by JakobGartner** [comment]
OK

yes, I agree after re-reading the SRS.

The end- markers only have significance for the processing on packet- level.
On MRSP level, they are not needed anymore. 

I know what to do :-) now.

On my backlog for next TA release

**Comment by Farhangi** [comment]
Hello @JakobGartner 

it looks like that the "MA sections" that are provided by TrackAtlas for SpeedSupervision, are not updated.
![commandtripbraking 32030](https://cloud.githubusercontent.com/assets/2284296/10908124/a2b8add6-822f-11e5-84fd-904bc38bf306.PNG)
![ma_list 32030](https://cloud.githubusercontent.com/assets/2284296/10908129/b0b19b50-822f-11e5-9dfc-b02d7c989b2e.png)
![mrsp_list 32030](https://cloud.githubusercontent.com/assets/2284296/10908141/c3eff824-822f-11e5-9d68-c3177c43641d.png)

**Comment by JakobGartner** [comment]
OK I confirm that I had only updated the MRSP length, but not for the MA.

Should work now.

**Comment by Farhangi** [comment]
It works now.
thank you!
